name: Node Continuous Integration
description: Runs e2e and unit tests, and builds a project

on:
  pull_request:
    branches: [main, production, development]
    
jobs:
  pull_request_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.16.0
      - name: Install dependancies
        run: yarn install
        run: yarn playwright install
      - name: Run unit tests
        run: yarn test
      - name: Run e2e tests
        run: yarn test:e2e
      - name: Run build
        run: yarn build
