name: Node Continuous Integration

on:
  pull_request:
    branches: [main, production, development]

jobs:
  pull_request_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.16.0
      - name: Installing dependancies
        run: yarn install && yarn playwright install
      - name: Running unit tests
        run: yarn test
      - name: Run e2e tests
        run: yarn test:e2e
      - name: Runnning build
        run: yarn build
