name: Node Continuous Integration

on:
  pull_request:
    branches: [main, production, development]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.16.0
      - run: yarn install
      - run: yarn test
      - run: yarn test:e2e
      - run: yarn build
